name: ci-notebooks
on:
  pull_request:
    paths:
      - modin/**
      - examples/tutorial/**
      - .github/workflows/ci-notebooks.yml
      - setup.cfg
      - setup.py
jobs:
  test-tutorial-notebooks:
    name: test tutorial notebooks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        execution: [pandas_on_ray, pandas_on_dask]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8.x"
          architecture: "x64"
      - name: Cache datasets
        uses: actions/cache@v2
        with:
          path: taxi.csv
          # update cache only if notebooks require it to be changed
          key: hashFiles("examples/tutorial/jupyter/**")
      # replace modin with . in the tutorial requirements file since we need
      # Modin built from sources
      - run: sed -i 's/modin/./g' examples/tutorial/jupyter/execution/${{ matrix.execution }}/requirements.txt
      # install dependencies required for notebooks execution
      - run: pip install -r examples/tutorial/jupyter/execution/${{ matrix.execution }}/requirements.txt
      # install test dependencies
      - run: pip install pytest pytest-cov black flake8 flake8-print flake8-no-implicit-concat
      - run: pip list
      - run: |
          black --check --diff examples/tutorial/jupyter/execution/${{ matrix.execution }}/test/test_notebooks.py
          black --check --diff examples/tutorial/jupyter/execution/test/utils.py
      - run: |
          flake8 --enable=T examples/tutorial/jupyter/execution/${{ matrix.execution }}/test/test_notebooks.py
          flake8 --enable=T examples/tutorial/jupyter/execution/test/utils.py
      - run: pytest examples/tutorial/jupyter/execution/${{ matrix.execution }}/test/test_notebooks.py

  test-notebooks-modin_on_omnisci:
    defaults:
      run:
        shell: bash -l {0}
    name: test notebooks modin_on_omnisci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Cache datasets
        uses: actions/cache@v2
        with:
          path: taxi.csv
          key: hashFiles("examples/tutorial/jupyter/execution/omnisci_on_native/local/**")
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: modin_on_omnisci
          environment-file: requirements/env_omnisci.yml
          python-version: 3.8
          channel-priority: strict
      - run: pip install .
      - run: conda install black flake8 flake8-print jupyter nbformat nbconvert -c conda-forge
      - run: conda list
      - run: black --check --diff examples/tutorial/jupyter/execution/omnisci_on_native/test/test_notebooks.py
      - run: flake8 --enable=T examples/tutorial/jupyter/execution/omnisci_on_native/test/test_notebooks.py
      - run: pytest examples/tutorial/jupyter/execution/omnisci_on_native/test/test_notebooks.py
